esphome:
  name: sgp40-dht22
  comment: Temperatrue and humidity compensated SGP40 sensor
  friendly_name: sgp40-dht22

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: DEBUG
  # level: INFO

# Enable Home Assistant API
api:

ota:
  password: "abcdefg-changeme"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sgp40-Dht22 Fallback Hotspot"
    password: "abcdefg-changeme"

captive_portal:

i2c:
  sda: SDA
  scl: SCL
  scan: True
  frequency: 1kHz
  
sensor:
  - platform: dht
    model: RHT03
    pin: D5
    temperature:
      name: "SGP40_Temperature"
      id: dht_temp
    accuracy_decimals: 2
    filters:
      - heartbeat: 1.0s # This helps sensors to trigger correctly to updates

    humidity:
      name: "SGP40_Humidity"
      id: dht_humidity
    update_interval: 30s
    accuracy_decimals: 2
    filters:
      - heartbeat: 1.0s # This helps sensors to trigger correctly to updates

  - platform: sgp4x # This is the new naming for the sensor
    name: "SGP40 VOC"
    id: air_quality_sensor
    i2c_id: bus_a # Set I2C bus
    address: 0x59 # Set the address for readability and debugging pruposes
    voc:
      name: "VOC Index"
      id: voc_index
    compensation:
      humidity_source: dht_humidity
      temperature_source: dht_temp
    update_interval: 30s
      
